FROM qqt-image-registry.tencentcloudcr.com/public-custom/nginx:tools
LABEL AUTH="qqt-ssl"
ADD dist /data/dist/
RUN set -eux && \
                /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
                echo 'Asia/Shanghai' >/etc/timezone
